version: '3.9'

services:
  gateway:
    build: ./gateway-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - auth
      - profile
      - community
      - post
      - interaction
      
  auth:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  profile:
    build: ./profile-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    depends_on:
      - auth

  community:
    build: ./community-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    depends_on:
      - auth

  post:
    build: ./post-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    depends_on:
      - community
      - auth

  interaction:
    build: ./interaction-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
    depends_on:
      - auth
      - post
